src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=512)
     */
    private $text;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 1,
     *      max = 5,
     *      notInRangeMessage = "Рейтинг должен быть от {{ min }} и до {{ max }}!",
     * )
     */
    private $rating;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $by_user;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $for_product;

    public function __construct()
    {
        $this->created_date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $createdDate): self
    {
        $this->created_date = $createdDate;

        return $this;
    }

    public function getByUser(): ?User
    {
        return $this->by_user;
    }

    public function setByUser(?User $by_user): self
    {
        $this->by_user = $by_user;

        return $this;
    }

    public function getForProduct(): ?Product
    {
        return $this->for_product;
    }

    public function setForProduct(?Product $for_product): self
    {
        $this->for_product = $for_product;

        return $this;
    }

    public function __toString()
    {
        return $this->by_user;
    }
}

src/Form/CommentType.php
<?php

namespace App\Form;

use App\Entity\Comment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('text', null, [
                'constraints' => [
                    new Length([
                        'min' => 10,
                        'minMessage' => 'Текст должен быть не менее {{ limit }} символов!',
                        'max' => 512
                    ])
                ],
                'label' => 'Отзыв',
                'attr' => [
                    'class' => 'validate'
                ]
            ])
            ->add('rating', NumberType::class, [
                'constraints' => [
                    new Length([
                        'max' => 1
                    ])
                ],
                'label' => 'Рейтинг',
                'attr' => [
                    'class' => 'validate',
                    'maxlength' => "1"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Comment::class,
        ]);
    }
}

templates/comment/_form.html.twig
<h5>Оставить отзыв</h5>
{{ form_start(form, {'attr':{'class':'col s12', 'accept-charset':'utf-8'}}) }}
    {% set formErrors = form.vars.errors.form.getErrors(true) %}
    {% if formErrors|length %}
        <div class="alert alert-danger">
            {% for error in formErrors %}
                <div class="materialert error">
                    <div class="material-icons">error_outline</div>
                    {{ error.message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="row">
        <div class="input-field col s12">
            {{ form_widget(form.text) }}
            {{ form_label(form.text) }}
        </div>
    </div>
    <div class="row">
        <div class="input-field col s12">
            {{ form_widget(form.rating) }}
            {{ form_label(form.rating) }}
        </div>
    </div>
    <div class="row">
        <div class="input-field col s12">
            <button class="btn waves-effect waves-light" style="float: left;" type="submit">Оставить отзыв<i class="material-icons right">send</i></button>
        </div>
    </div>
{{ form_end(form) }}

templates/comment/_index.html.twig
<h5>Отзывы</h5>
<table class="table">
    <tbody>
    {% for comment in pagination %}
        <tr>
            <td colspan="3"><b>{{ comment.byUser.name }}</b></td>
        </tr>
        <tr>
            <td>{{ comment.text }}</td>
            <td>
                <form id="product_rating">
                    <div id="show_stars" class="stars">
                        <input  type="radio" name="star" class="star-1" id="star-1" {% if comment.getRating is same as(1) %}checked{% else %}disabled{% endif %}/>
                        <label class="star-1" for="star-1">1</label>
                        <input type="radio" name="star" class="star-2" id="star-2" {% if comment.getRating is same as(2) %}checked{% else %}disabled{% endif %}/>
                        <label class="star-2" for="star-2">2</label>
                        <input type="radio" name="star" class="star-3" id="star-3" {% if comment.getRating is same as(3) %}checked{% else %}disabled{% endif %}/>
                        <label class="star-3" for="star-3">3</label>
                        <input type="radio" name="star" class="star-4" id="star-4" {% if comment.getRating is same as(4) %}checked{% else %}disabled{% endif %}/>
                        <label class="star-4" for="star-4">4</label>
                        <input type="radio" name="star" class="star-5" id="star-5" {% if comment.getRating is same as(5) %}checked{% else %}disabled{% endif %}/>
                        <label class="star-5" for="star-5">5</label>
                        <span></span>
                    </div>
                </form>
            </td>
            <td>{{ comment.createdDate ? comment.createdDate|date('Y-m-d H:i:s') : '' }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<div class="row">
    <div class="col s12 center-align">
        {{ knp_pagination_render(pagination) }}
    </div>
</div>

templates/comment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Comment{% endblock %}

{% block body %}
    <h1>Create new Comment</h1>

    {{ include('comment/_form.html.twig') }}

    <a href="{{ path('comment_index') }}">back to list</a>
{% endblock %}