src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 * @Vich\Uploadable()
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=512)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date;

    /**
     * @ORM\Column(type="string", length=512)
     */
    private $thumbnailName;

    /**
     * @Assert\File(
     *     maxSize = "10M",
     *     mimeTypes = {
     *         "image/jpeg",
     *         "image/gif",
     *         "image/png",
     *     }
     * )
     * @Vich\UploadableField(mapping="products_thumbnails", fileNameProperty="thumbnailName")
     */
    private $thumbnailFile;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="for_product", cascade={"remove"})
     */
    private $comments;

    public function __construct()
    {
        $this->created_date = new \DateTime();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDateValue()
    {
        $this->created_date = new \DateTime();
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setForProduct($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getForProduct() === $this) {
                $comment->setForProduct(null);
            }
        }

        return $this;
    }

    public function getCommentsCount(): int
    {
        return $this->comments->count();
    }

    public function getRating() : int
    {
        $count = 0;
        foreach ($this->comments as $comment) {
            $count += $comment->getRating();
        }
        if ($this->getCommentsCount() == 0) {
            return 0;
        }
        return (int) $count / $this->getCommentsCount();
    }

    public function getThumbnailFile()
    {
        return $this->thumbnailFile;
    }

    /**
     * @param $thumbnailFile
     */
    public function setThumbnailFile($thumbnailFile): void
    {
        $this->thumbnailFile = $thumbnailFile;
    }

    public function getThumbnailName(): ?string
    {
        return $this->thumbnailName;
    }

    public function setThumbnailName(?string $thumbnailName): self
    {
        $this->thumbnailName = $thumbnailName;

        return $this;
    }

    public function getThumbnailFileFullPath(): string
    {
        return '/uploads/' . $this->getThumbnailName();
    }

    public function __toString()
    {
        return $this->name;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Product;
use App\Form\CommentType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/product")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/{id}", name="product_show", methods={"GET", "POST"})
     * @param Product $product
     * @param EntityManagerInterface $em
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @param Security $security
     * @return Response
     */
    public function show(Product $product, EntityManagerInterface $em, PaginatorInterface $paginator, Request $request, Security $security): Response
    {
        // get all Product objects
        $query = $em->createQuery(
            'SELECT c
            FROM App\Entity\Comment c
            WHERE c.for_product = :for_product
            ORDER BY c.created_date DESC'
        )->setParameter('for_product', $product);

        // set default sort and  direction properties
        $request->query->set('sort', 'c.created_date');
        $request->query->set('direction', 'desc');
        // get page number
        $page_number = $request->query->getInt('page', 1);
        // set correct pager number
        if ($page_number < 1) {
            $page_number = 1;
        }
        // paginate
        $pagination = $paginator->paginate(
            $query,
            $page_number,
            5
        );
        // create new comment
        $comment = new Comment();
        $comment->setForProduct($product);
        $comment->setByUser($security->getUser());
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        // check form
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();
            return $this->redirectToRoute('product_show', ['id' => $product->getId()]);
        }

        // render view
        return $this->render('product/show.html.twig', [
            'product' => $product,
            'pagination' => $pagination,
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }
}

templates/product/_index.html.twig
<div class="row"></div>
<div class="row" style="width: 100%">
    {% for product in pagination %}
        <div class="col l4 m6 s12">
            <a href="/product/{{ product.id }}">
                <div class="card medium">
                    <div class="card-image">
                        <img class="responsive-img" src="uploads/{{ product.thumbnailName }}">
                        <span class="card-title black-text">{{ product.name }}</span>
                    </div>
                    <div class="card-content center-align">
                        <form id="product{{ product.id }}_rating">
                            <div id="show_stars" class="stars">
                                <input  type="radio" name="star" class="star-1" id="star-1" {% if product.getRating is same as(1) %}checked{% else %}disabled{% endif %}/>
                                <label class="star-1" for="star-1">1</label>
                                <input type="radio" name="star" class="star-2" id="star-2" {% if product.getRating is same as(2) %}checked{% else %}disabled{% endif %}/>
                                <label class="star-2" for="star-2">2</label>
                                <input type="radio" name="star" class="star-3" id="star-3" {% if product.getRating is same as(3) %}checked{% else %}disabled{% endif %}/>
                                <label class="star-3" for="star-3">3</label>
                                <input type="radio" name="star" class="star-4" id="star-4" {% if product.getRating is same as(4) %}checked{% else %}disabled{% endif %}/>
                                <label class="star-4" for="star-4">4</label>
                                <input type="radio" name="star" class="star-5" id="star-5" {% if product.getRating is same as(5) %}checked{% else %}disabled{% endif %}/>
                                <label class="star-5" for="star-5">5</label>
                                <span></span>
                            </div>
                        </form>
                    </div>
                    <div class="card-action">
                        <div class="row">
                            <div class="col s5">
                                <div class="row">
                                    <div class="col s1">
                                        <i class="material-icons">comment</i>
                                    </div>
                                    <div class="col s1" style="margin-left: 5px">
                                        {{ product.getCommentsCount() }}
                                    </div>
                                </div>
                            </div>
                            <div class="col s7">
                                <div class="row">
                                    <div class="col s2">
                                        <i class="material-icons">date_range</i>
                                    </div>
                                    <div class="col s10">
                                        {{ product.createdDate|date('d-m-Y H:i:s') }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
<div class="row">
    <div class="col s12 center-align">
        {{ knp_pagination_render(pagination) }}
    </div>
</div>

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <div class="row"></div>
    <div class="row">
        <div class="col s12">
            <h4>{{ product.name }}</h4>
        </div>
    </div>
    <table class="table">
        <tbody>
            <tr>
                <th>Описание</th>
                <td>{{ product.description }}</td>
            </tr>
            <tr>
                <th>Дата добавления</th>
                <td>{{ product.createdDate ? product.createdDate|date('d-m-Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Фото</th>
                <td><img class="responsive-img" src="{{ product.getThumbnailFileFullPath }}"></td>
            </tr>
            <tr>
                <th>Количество оценок</th>
                <td>{{ product.getCommentsCount() }}</td>
            </tr>
            <tr>
                <th>Рейтинг</th>
                <td>
                    <div class="row">
                        <div class="col s12 left-align" style="width: 200px; margin-left: -30px">
                            <form id="product_rating">
                                <div id="show_stars" class="stars">
                                    <input  type="radio" name="star" class="star-1" id="star-1" {% if product.getRating is same as(1) %}checked{% else %}disabled{% endif %}/>
                                    <label class="star-1" for="star-1">1</label>
                                    <input type="radio" name="star" class="star-2" id="star-2" {% if product.getRating is same as(2) %}checked{% else %}disabled{% endif %}/>
                                    <label class="star-2" for="star-2">2</label>
                                    <input type="radio" name="star" class="star-3" id="star-3" {% if product.getRating is same as(3) %}checked{% else %}disabled{% endif %}/>
                                    <label class="star-3" for="star-3">3</label>
                                    <input type="radio" name="star" class="star-4" id="star-4" {% if product.getRating is same as(4) %}checked{% else %}disabled{% endif %}/>
                                    <label class="star-4" for="star-4">4</label>
                                    <input type="radio" name="star" class="star-5" id="star-5" {% if product.getRating is same as(5) %}checked{% else %}disabled{% endif %}/>
                                    <label class="star-5" for="star-5">5</label>
                                    <span></span>
                                </div>
                            </form>
                        </div>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="row"></div>
    <a href="{{ app.request.headers.get('referer') }}" class="btn waves-effect waves-light" style="float: left; width: 120px"><i class="material-icons left">arrow_back</i>Назад</a>
    <div class="row"></div>
    {{ include('comment/_form.html.twig') }}
    <div class="row"></div>
    {{ include('comment/_index.html.twig') }}
{% endblock %}